version: "3.8"

services:
  database:
    container_name: database1
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=shopify_backend_development
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=shopify_shops
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db:
